#ifndef FYRE_CHAINPARAMSSEEDS_H
#define FYRE_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the fyre network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
 // ***TODO*** fix generate-seeds.py and REGENERATE
static SeedSpec6 pnSeed6_main[] = {
    {NULL, NULL}
};

static SeedSpec6 pnSeed6_test[] = {
    {NULL, NULL}
};
#endif // FYRE_CHAINPARAMSSEEDS_H
